#kind: Service
#apiVersion: v1
#metadata:
#  name: auth-service
#  labels:
#    run: auth-service
#spec:
#  type: NodePort
#  selector:
#    app: user-service
#  ports:
#    - port: 5050
#      protocol: TCP





apiVersion: v1
kind: Service
metadata:
  name: auth-service-srv
  labels:
    app: auth-service
spec:
  type: NodePort
  ports:
  - port: 5050
    name: http
  selector:
    app: auth-service