apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: generator-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: generator-service
        version: v1
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: bucket-service-account
      containers:
      - name: sample-service
        image: gcr.io/samplergan/generator-service@sha256:f6ac1fc6c2fa1813c5bb5ba5d677208d444d66eb39f3bd3cbcf48440cbb30f19
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        ports:
        - containerPort: 5025
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5025
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
          - name: AUTH_SERVER
            value: 'http://wisebeatstudio.com'
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json