apiVersion: v1
kind: Service
metadata:
  name: metadata-service-srv
  labels:
    app: metadata-service
spec:
  type: NodePort
  ports:
  - port: 5099
    name: http
  selector:
    app: metadata-service
