apiVersion: v1
kind: Service
metadata:
  name: sample-service-srv
  labels:
    app: sample-service
spec:
  type: LoadBalancer
  ports:
  - port: 5020
    name: tcp
  selector:
    app: sample-service