kind: Service
apiVersion: v1
metadata:
  name: sample-service
  labels:
    run: sample-service
spec:
  type: NodePort
  selector:
    app: sample-service
  ports:
    - port: 5020
      protocol: TCP
